import {neon} from "@neondatabase/serverless";
type Game={key:string;icon:string;title_en:string;title_ar:string;subtitle_en:string;subtitle_ar:string;kind:string;payload:any;sort_order:number};
const fallback:Game[]=[
{key:"plate",icon:"🍽️",title_en:"Build My Plate",title_ar:"اعمل وجبتك",subtitle_en:"Build + detect",subtitle_ar:"كوّن واكتشف",kind:"builder",sort_order:0,payload:{foods:[["🥖","Bread","عيش",true],["🍚","Rice","أرز",true],["🍝","Pasta","مكرونة",true],["🥔","Potato","بطاطس",true],["🫘","Ful","فول",true],["🍎","Apple","تفاح",true],["🥛","Yogurt","زبادي",true],["🍗","Chicken","فراخ",false],["🥚","Egg","بيض",false],["🥒","Cucumber","خيار",false],["🥦","Broccoli","بروكلي",false],["🐟","Fish","سمك",false]]}},
{key:"shop",icon:"🛒",title_en:"Supermarket Hunt",title_ar:"مهمة السوبرماركت",subtitle_en:"Find the label clue",subtitle_ar:"دور على المعلومة",kind:"label",sort_order:1,payload:{rows:[["Energy","الطاقة","380 kcal","380 سعر"],["Protein","البروتين","7 g","7 جم"],["Total Carbohydrate","إجمالي الكربوهيدرات","68 g","68 جم"],["Fat","الدهون","8 g","8 جم"]],answer:"Total Carbohydrate"}},
{key:"lunch",icon:"🎒",title_en:"Pack My Lunchbox",title_ar:"حضّر شنطتك",subtitle_en:"Pack + discover",subtitle_ar:"اختار واكتشف",kind:"builder",sort_order:2,payload:{foods:[["🥖","Bread","عيش",true],["🧀","Cheese","جبنة",false],["🥒","Cucumber","خيار",false],["🍌","Banana","موز",true],["🥛","Milk","لبن",true],["🥚","Egg","بيضة",false],["🍎","Apple","تفاح",true]]}},
{key:"koshari",icon:"🍲",title_en:"Koshari Builder",title_ar:"اعمل طبق كشري",subtitle_en:"Spot every source",subtitle_ar:"اكتشف كل المصادر",kind:"mixed-dish",sort_order:3,payload:{ingredients:[["🍚","Rice","أرز"],["🍝","Pasta","مكرونة"],["🫘","Lentils","عدس"],["🫛","Chickpeas","حمص"],["🍅","Tomato sauce","صلصة طماطم"],["🧅","Crispy onion","بصل مقرمش"]]}},
{key:"portion",icon:"✋",title_en:"Portion Match",title_ar:"تحدي الحصة",subtitle_en:"Match the amount",subtitle_ar:"طابق الكمية",kind:"quiz",sort_order:4,payload:{options_en:["⅓ cup cooked rice","A full koshari plate","Plain chicken"],options_ar:["⅓ كوب أرز مطبوخ","طبق كشري كامل","قطعة فراخ سادة"],answer:0}}
];
function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function load(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS public.learning_games (key text PRIMARY KEY,icon text NOT NULL,title_en text NOT NULL,title_ar text NOT NULL,subtitle_en text NOT NULL,subtitle_ar text NOT NULL,kind text NOT NULL,payload jsonb NOT NULL,is_active boolean NOT NULL DEFAULT true,sort_order integer NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now())`;for(const g of fallback){await sql`INSERT INTO public.learning_games (key,icon,title_en,title_ar,subtitle_en,subtitle_ar,kind,payload,sort_order,updated_at) VALUES (${g.key},${g.icon},${g.title_en},${g.title_ar},${g.subtitle_en},${g.subtitle_ar},${g.kind},${JSON.stringify(g.payload)}::jsonb,${g.sort_order},now()) ON CONFLICT (key) DO UPDATE SET icon=EXCLUDED.icon,title_en=EXCLUDED.title_en,title_ar=EXCLUDED.title_ar,subtitle_en=EXCLUDED.subtitle_en,subtitle_ar=EXCLUDED.subtitle_ar,kind=EXCLUDED.kind,payload=EXCLUDED.payload,sort_order=EXCLUDED.sort_order,updated_at=now()`}return sql`SELECT key,icon,title_en,title_ar,subtitle_en,subtitle_ar,kind,payload,sort_order FROM public.learning_games WHERE is_active=true ORDER BY sort_order,key`}
export async function GET(){let games:any[]=fallback,source="fallback";try{const rows=await load();if(rows.length){games=rows;source="database"}}catch(error){console.error("learning games GET failed",error)}return Response.json({games,total:games.length,source},{headers:{"Cache-Control":"public, s-maxage=3600, stale-while-revalidate=86400"}})}
