import {neon} from "@neondatabase/serverless";
import {currentUser} from "../../../../lib/auth/server";
const fallback=["baladi-bread","عيش بلدي","Bread & grains","1 medium piece","≈ 30 g"];
function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function admin(){const u=await currentUser();if(!u)return null;const allowed=(process.env.ADMIN_EMAILS||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);return u.email&&allowed.includes(u.email.toLowerCase())?u:null}
async function ensure(sql:any){await sql`CREATE TABLE IF NOT EXISTS public.foods (id text PRIMARY KEY,name text NOT NULL,category text NOT NULL,portion text NOT NULL,carbohydrate text NOT NULL,source text NOT NULL DEFAULT 'NutClue educational reference',confidence text NOT NULL DEFAULT 'estimated',reviewed_at timestamptz,reviewed_by text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`;await sql`ALTER TABLE public.foods ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'NutClue educational reference'`;await sql`ALTER TABLE public.foods ADD COLUMN IF NOT EXISTS confidence text NOT NULL DEFAULT 'estimated'`}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){try{const u=await admin();if(!u)return json({error:"Forbidden"},403);const sql=db();await ensure(sql);const rows=await sql`SELECT id,name,category,portion,carbohydrate,source,confidence,reviewed_at,updated_at FROM public.foods ORDER BY name`;return json({foods:rows})}catch(e){console.error("admin foods GET failed",e);return json({error:"Unable to load foods"},500)}}
export async function POST(request:Request){try{const u=await admin();if(!u)return json({error:"Forbidden"},403);const body=await request.json();const id=String(body.id||"").trim().slice(0,60),name=String(body.name||"").trim().slice(0,120),category=String(body.category||"").trim().slice(0,60),portion=String(body.portion||"").trim().slice(0,80),carbohydrate=String(body.carbohydrate||"").trim().slice(0,80),source=String(body.source||"NutClue educational reference").trim().slice(0,160),confidence=String(body.confidence||"estimated").trim().slice(0,30);if(!id||!name||!category||!portion||!carbohydrate)return json({error:"All food fields are required"},400);const sql=db();await ensure(sql);const rows=await sql`INSERT INTO public.foods (id,name,category,portion,carbohydrate,source,confidence,reviewed_at,reviewed_by) VALUES (${id},${name},${category},${portion},${carbohydrate},${source},${confidence},now(),${u.email}) ON CONFLICT (id) DO UPDATE SET name=${name},category=${category},portion=${portion},carbohydrate=${carbohydrate},source=${source},confidence=${confidence},reviewed_at=now(),reviewed_by=${u.email},updated_at=now() RETURNING id,name,category,portion,carbohydrate,source,confidence,reviewed_at,updated_at`;return json({food:rows[0]},201)}catch(e){console.error("admin foods POST failed",e);return json({error:"Unable to save food"},500)}}
export async function DELETE(request:Request){try{const u=await admin();if(!u)return json({error:"Forbidden"},403);const id=String((await request.json()).id||"").trim();if(!id)return json({error:"id is required"},400);const sql=db();await ensure(sql);await sql`DELETE FROM public.foods WHERE id=${id}`;return json({ok:true})}catch(e){console.error("admin foods DELETE failed",e);return json({error:"Unable to delete food"},500)}}
