import {neon} from "@neondatabase/serverless";
const fallback=[
{id:"carbs",eyebrow_en:"CARBS",eyebrow_ar:"كربوهيدرات",title_en:"Carbohydrates, without the drama.",title_ar:"الكربوهيدرات من غير تعقيد.",body_en:"Carbohydrate is one of the main nutrients in food. Instead of labelling foods good or bad, start with what the food contains, the portion, and what else is in the meal.",body_ar:"الكربوهيدرات عنصر أساسي في الأكل. بدل ما نصنّف الأكل كويس أو وحش، ابدأ بالمكوّن والكمية وباقي الوجبة.",practical_en:"Start with the portion in front of you. Bread, rice, pasta, fruit, milk and legumes can all contribute carbohydrate.",practical_ar:"ابدأ بالكمية اللي قدامك. العيش والأرز والمكرونة والفاكهة واللبن والبقوليات ممكن تضيف كربوهيدرات.",sort_order:0},
{id:"food",eyebrow_en:"FOOD A–Z",eyebrow_ar:"دليل الأكل",title_en:"Food you actually know.",title_ar:"أكل إنت عارفه.",body_en:"Build understanding around familiar foods rather than perfect meal plans. Compare portions, ingredients and preparation methods.",body_ar:"ابنِ فهمك على الأكلات المألوفة بدل خطط مثالية. قارن بين الكميات والمكونات وطريقة التحضير.",practical_en:"A baladi bread, a bowl of lentils and a piece of fruit can all fit into useful food conversations — context matters.",practical_ar:"عيش بلدي وطبق عدس وقطعة فاكهة كلهم ينفعوا يكونوا جزءًا من نقاش مفيد عن الأكل؛ السياق مهم.",sort_order:1},
{id:"labs",eyebrow_en:"LABS",eyebrow_ar:"تحاليل",title_en:"Make sense of the language.",title_ar:"افهم اللغة الطبية.",body_en:"Lab results are most useful when interpreted with your clinician alongside symptoms, medicines, history and trends.",body_ar:"التحاليل بتكون مفيدة أكتر لما تتناقش مع الطبيب مع الأعراض والأدوية والتاريخ والاتجاهات.",practical_en:"Write down the test name, value, unit and date. Bring the actual report to your visit rather than relying on memory.",practical_ar:"اكتب اسم التحليل والقيمة والوحدة والتاريخ، وخد التقرير الأصلي معاك للزيارة.",sort_order:2},
{id:"patterns",eyebrow_en:"WAYS OF EATING",eyebrow_ar:"طرق الأكل",title_en:"Beyond diet hype.",title_ar:"بعيدًا عن هوس الحميات.",body_en:"Eating patterns describe combinations of foods over time. One label never tells the whole story.",body_ar:"أنماط الأكل هي مجموعات أكل بتمتد مع الوقت. ملصق واحد مش بيحكي القصة كلها.",practical_en:"Look for patterns you can actually maintain: vegetables, whole foods, useful protein sources, fibre and an approach that fits your context.",practical_ar:"دور على نمط تقدر تستمر عليه: خضروات، أكل كامل، مصادر بروتين وألياف، وطريقة تناسب حياتك.",sort_order:3}
];
function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function load(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS public.learning_guides (id text PRIMARY KEY,eyebrow_en text NOT NULL,eyebrow_ar text NOT NULL,title_en text NOT NULL,title_ar text NOT NULL,body_en text NOT NULL,body_ar text NOT NULL,practical_en text NOT NULL,practical_ar text NOT NULL,is_active boolean NOT NULL DEFAULT true,sort_order integer NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now())`;for(const g of fallback){await sql`INSERT INTO public.learning_guides (id,eyebrow_en,eyebrow_ar,title_en,title_ar,body_en,body_ar,practical_en,practical_ar,sort_order,updated_at) VALUES (${g.id},${g.eyebrow_en},${g.eyebrow_ar},${g.title_en},${g.title_ar},${g.body_en},${g.body_ar},${g.practical_en},${g.practical_ar},${g.sort_order},now()) ON CONFLICT (id) DO UPDATE SET eyebrow_en=EXCLUDED.eyebrow_en,eyebrow_ar=EXCLUDED.eyebrow_ar,title_en=EXCLUDED.title_en,title_ar=EXCLUDED.title_ar,body_en=EXCLUDED.body_en,body_ar=EXCLUDED.body_ar,practical_en=EXCLUDED.practical_en,practical_ar=EXCLUDED.practical_ar,sort_order=EXCLUDED.sort_order,updated_at=now()`}return sql`SELECT id,eyebrow_en,eyebrow_ar,title_en,title_ar,body_en,body_ar,practical_en,practical_ar FROM public.learning_guides WHERE is_active=true ORDER BY sort_order,id`}
export async function GET(){let guides:any[]=fallback,source="fallback";try{const rows=await load();if(rows.length){guides=rows;source="database"}}catch(error){console.error("learning guides GET failed",error)}return Response.json({guides,total:guides.length,source},{headers:{"Cache-Control":"public, s-maxage=3600, stale-while-revalidate=86400"}})}
