"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {authClient} from "../../lib/auth/client";
type Profile={id:string;nickname:string;age_band:string;consent_at:string};
type Progress={game_key:string;completed:boolean;score:number;updated_at:string};
const ageLabels={"under-8":"أقل من ٨","8-12":"٨–١٢","13-17":"١٣–١٧"};
export default function ParentPage(){
 const {data:session}=authClient.useSession();
 const [profile,setProfile]=useState<Profile|null>(null),[progress,setProgress]=useState<Progress[]>([]),[nickname,setNickname]=useState(""),[ageBand,setAgeBand]=useState("8-12"),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!session)return;Promise.all([fetch("/api/child-profile").then(r=>r.ok?r.json():null),fetch("/api/progress").then(r=>r.ok?r.json():null)]).then(([p,g])=>{const next=p?.profiles?.[0];if(next){setProfile(next);setNickname(next.nickname);setAgeBand(next.age_band);setConsent(true)}if(g?.progress)setProgress(g.progress)}).catch(()=>setMessage("تعذر تحميل مساحة العائلة."))},[session]);
 if(!session)return <main className="parentPage" dir="rtl"><section className="parentCard"><Link href="/" className="authBrand">ILAMA <span>BLOOM</span></Link><small>مساحة الأهل</small><h1>طريقة أهدى لدعم التعلّم.</h1><p>سجّل الدخول لإنشاء ملف تعلّم اختياري للطفل. نحفظ اسمًا مستعارًا، والفئة العمرية، والتقدم التعليمي فقط — من غير ملف عام أو ترتيب أو هدف وزن.</p><Link className="parentPrimary" href="/auth/sign-in?next=%2Fparent">دخول للمتابعة ←</Link></section></main>;
 const save=async()=>{setBusy(true);setMessage("");const r=await fetch("/api/child-profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname,ageBand,consent})});const data=await r.json().catch(()=>null);setBusy(false);if(data?.profile){setProfile(data.profile);setMessage("تم حفظ ملف العائلة.");}else setMessage(data?.error||"تعذر حفظ الملف.")};
 const remove=async()=>{setBusy(true);await fetch("/api/child-profile",{method:"DELETE"});setBusy(false);setProfile(null);setNickname("");setConsent(false);setMessage("تم حذف ملف الطفل.");};
 return <main className="parentPage" dir="rtl"><section className="parentCard"><Link href="/" className="authBrand">ILAMA <span>BLOOM</span></Link><small>مساحة الأهل</small><h1>{profile?"مساحة عائلتك.":"أنشئ ملف تعلّم."}</h1><p>التقدم التعليمي يظل خاصًا بحسابك. هذا ملف تعليمي، وليس سجلًا طبيًا أو متابعًا للعلاج.</p><div className="parentForm"><label>اسم مستعار<input maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="مثال: نور"/></label><label>الفئة العمرية<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}>{Object.entries(ageLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="consentRow"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>أنا ولي الأمر وأوافق على حفظ ملف التعلّم المحدود ده.</span></label><button className="parentPrimary" disabled={busy||!nickname.trim()||!consent} onClick={save}>{busy?"جارٍ الحفظ…":"احفظ الملف"}</button>{profile&&<button className="parentDanger" disabled={busy} onClick={remove}>احذف ملف الطفل</button>}<p className="parentMessage" aria-live="polite">{message}</p></div>{progress.length>0&&<section className="progressPanel"><small>التقدم التعليمي</small>{progress.map(item=><div key={item.game_key}><b>{item.game_key}</b><span>{item.completed?"مكتمل":"قيد التقدم"} · {item.score} نقطة</span></div>)}</section>}<Link href="/" className="parentBack">العودة إلى Ilama Bloom ←</Link></section></main>
}

