"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {authClient} from "../../lib/auth/client";

type Profile={id:string;nickname:string;age_band:string;consent_at:string};
type Progress={game_key:string;completed:boolean;score:number;updated_at:string};
const ageLabels={"under-8":"Under 8","8-12":"8–12","13-17":"13–17"};

export default function ParentPage(){
 const {data:session}=authClient.useSession();
 const [profile,setProfile]=useState<Profile|null>(null),[progress,setProgress]=useState<Progress[]>([]),[nickname,setNickname]=useState(""),[ageBand,setAgeBand]=useState("8-12"),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!session)return;Promise.all([fetch("/api/child-profile").then(r=>r.ok?r.json():null),fetch("/api/progress").then(r=>r.ok?r.json():null)]).then(([p,g])=>{const next=p?.profiles?.[0];if(next){setProfile(next);setNickname(next.nickname);setAgeBand(next.age_band);setConsent(true)}if(g?.progress)setProgress(g.progress)}).catch(()=>setMessage("Unable to load your family space."))},[session]);
 if(!session)return <main className="parentPage"><section className="parentCard"><Link href="/" className="authBrand">NUT<span>CLUE</span></Link><small>CAREGIVER SPACE</small><h1>A calmer way to support learning.</h1><p>Sign in to create an optional child learning profile. NutClue stores only a nickname, age band and learning progress — never a public profile, leaderboard or weight goal.</p><Link className="parentPrimary" href="/auth/sign-in?next=%2Fparent">Sign in to continue →</Link></section></main>;
 const save=async()=>{setBusy(true);setMessage("");const r=await fetch("/api/child-profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname,ageBand,consent})});const data=await r.json().catch(()=>null);setBusy(false);if(data?.profile){setProfile(data.profile);setMessage("Family profile saved.");}else setMessage(data?.error||"Could not save the profile.")};
 const remove=async()=>{setBusy(true);await fetch("/api/child-profile",{method:"DELETE"});setBusy(false);setProfile(null);setNickname("");setConsent(false);setMessage("Child profile removed.");};
 return <main className="parentPage"><section className="parentCard"><Link href="/" className="authBrand">NUT<span>CLUE</span></Link><small>CAREGIVER SPACE</small><h1>{profile?"Your family space.":"Create a learning profile."}</h1><p>Learning progress stays private to your account. This is an educational profile, not a medical record and not a treatment tracker.</p><div className="parentForm"><label>Nickname<input maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="e.g. Noor"/></label><label>Age band<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}>{Object.entries(ageLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="consentRow"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I am the caregiver and agree to save this minimal learning profile.</span></label><button className="parentPrimary" disabled={busy||!nickname.trim()||!consent} onClick={save}>{busy?"Saving…":"Save profile"}</button>{profile&&<button className="parentDanger" disabled={busy} onClick={remove}>Remove child profile</button>}<p className="parentMessage" aria-live="polite">{message}</p></div>{progress.length>0&&<section className="progressPanel"><small>LEARNING PROGRESS</small>{progress.map(item=><div key={item.game_key}><b>{item.game_key}</b><span>{item.completed?"Completed":"In progress"} · {item.score} points</span></div>)}</section>}<Link href="/" className="parentBack">Back to NutClue →</Link></section></main>
}

