import {neon} from "@neondatabase/serverless";

const fallback=[
 {id:"label-serving",kind:"label",title_en:"Start with the serving",title_ar:"ابدأ بالحصة",prompt_en:"A label lists nutrition per serving. What should you check before comparing the numbers?",prompt_ar:"البطاقة بتعرض القيم لكل حصة. إيه أول حاجة تراجعها قبل مقارنة الأرقام؟",options_en:["Serving size","Package colour","Brand logo"],options_ar:["حجم الحصة","لون العبوة","شعار الشركة"],answer:0,explanation_en:"The serving size tells you what amount the listed values describe.",explanation_ar:"حجم الحصة بيحدد الكمية اللي الأرقام المكتوبة بتوصفها."},
 {id:"label-100g",kind:"label",title_en:"Per 100 g detective",title_ar:"محقق كل 100 جم",prompt_en:"A label gives values per 100 g. What else do you need to use them for your food?",prompt_ar:"البطاقة كاتبة القيم لكل 100 جم. إيه المعلومة التانية اللي تحتاجها؟",options_en:["The amount you use","The shop name","The package shape"],options_ar:["الكمية اللي هتستخدمها","اسم المتجر","شكل العبوة"],answer:0,explanation_en:"Relate the per-100 g value to the amount you actually use.",explanation_ar:"اربط قيمة كل 100 جم بالكمية الفعلية اللي هتستخدمها."},
 {id:"mixed-koshari",kind:"mixed-dish",title_en:"Mixed dish detective",title_ar:"محقق الطبق المركب",prompt_en:"Why can two plates of koshari have different nutrition estimates?",prompt_ar:"ليه طبقين كشري ممكن يكون لهم تقدير غذائي مختلف؟",options_en:["Recipe and portion can differ","The plate colour changes it","Only the time matters"],options_ar:["الوصفة والكمية ممكن يختلفوا","لون الطبق بيغيره","الوقت فقط هو المهم"],answer:0,explanation_en:"Mixed dishes vary with ingredients, recipe and portion, so estimates need context.",explanation_ar:"الأطباق المركبة بتختلف حسب المكونات والوصفة والكمية، لذلك التقدير محتاج سياق."},
 {id:"product-label",kind:"atlas",title_en:"Specific beats general",title_ar:"المنتج الفعلي أدق",prompt_en:"The Atlas estimate differs from the current label on a packaged food. Which is more specific to that product?",prompt_ar:"تقدير الدليل مختلف عن البطاقة الحالية لمنتج معبأ. أنهي مرجع أخص بالمنتج نفسه؟",options_en:["The current product label","Always the general Atlas","Average both"],options_ar:["بطاقة المنتج الحالية","الدليل العام دائمًا","متوسط الاثنين"],answer:0,explanation_en:"For packaged food, the current label describes that specific product and serving information.",explanation_ar:"للأكل المعبأ، البطاقة الحالية بتوصف نفس المنتج ومعلومات الحصة الخاصة به."}
];

function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.ILAMA_BLOOM_DATABASE_URL||process.env.ILAMA_BLOOM_POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function load(){const sql=db();await sql`CREATE TABLE IF NOT EXISTS public.learning_missions (id text PRIMARY KEY,kind text NOT NULL,title_en text NOT NULL,title_ar text NOT NULL,prompt_en text NOT NULL,prompt_ar text NOT NULL,options_en jsonb NOT NULL,options_ar jsonb NOT NULL,answer integer NOT NULL,explanation_en text NOT NULL,explanation_ar text NOT NULL,is_active boolean NOT NULL DEFAULT true,sort_order integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`;for(const [i,m] of fallback.entries()){await sql`INSERT INTO public.learning_missions (id,kind,title_en,title_ar,prompt_en,prompt_ar,options_en,options_ar,answer,explanation_en,explanation_ar,sort_order,updated_at) VALUES (${m.id},${m.kind},${m.title_en},${m.title_ar},${m.prompt_en},${m.prompt_ar},${JSON.stringify(m.options_en)}::jsonb,${JSON.stringify(m.options_ar)}::jsonb,${m.answer},${m.explanation_en},${m.explanation_ar},${i},now()) ON CONFLICT (id) DO NOTHING`}return sql`SELECT id,kind,title_en,title_ar,prompt_en,prompt_ar,options_en,options_ar,answer,explanation_en,explanation_ar FROM public.learning_missions WHERE is_active=true ORDER BY sort_order,id`}
export async function GET(){let missions:any[]=fallback,source="fallback";try{const rows=await load();if(rows.length){missions=rows;source="database"}}catch(error){console.error("learning missions GET failed",error)}return Response.json({missions,total:missions.length,source},{headers:{"Cache-Control":source==="database"?"public, s-maxage=3600, stale-while-revalidate=86400":"public, s-maxage=60, stale-while-revalidate=300"}})}
