import {neon} from "@neondatabase/serverless";
import {currentUser} from "../../../lib/auth/server";
 function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.ILAMA_BLOOM_DATABASE_URL||process.env.ILAMA_BLOOM_POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function user(){return currentUser()}
async function ensure(sql:any){await sql`CREATE TABLE IF NOT EXISTS public.entries (id text PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), user_id text NOT NULL, type text NOT NULL, value text NOT NULL, at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE INDEX IF NOT EXISTS entries_user_at_idx ON public.entries (user_id, at DESC)`}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){try{const u=await user();if(!u)return json({entries:[],error:"Unauthorized"},401);const sql=db();await ensure(sql);const rows=await sql`SELECT id,type,value,at FROM public.entries WHERE user_id=${u.id} ORDER BY at DESC LIMIT 300`;return json({entries:rows})}catch(error){console.error("entries GET failed",error);return json({error:"Unable to load entries"},500)}}
export async function POST(request:Request){try{const u=await user();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);const body=await request.json().catch(()=>null);if(!body)return json({error:"Invalid JSON"},400);const type=String(body.type||"").trim().slice(0,80),value=String(body.value||"").trim().slice(0,180),rawAt=String(body.at||new Date().toISOString()),timestamp=Date.parse(rawAt);if(!type||!value||Number.isNaN(timestamp))return json({error:"Invalid entry"},400);const now=Date.now();if(timestamp>now+86400000||timestamp<now-315576000000)return json({error:"Entry date is outside the supported range"},400);const rows=await sql`INSERT INTO public.entries (user_id,type,value,at) VALUES (${u.id},${type},${value},${new Date(timestamp).toISOString()}) RETURNING id,type,value,at`;return json({entry:rows[0]},201)}catch(error){console.error("entries POST failed",error);return json({error:"Unable to save entry"},500)}}
export async function PATCH(request:Request){try{const u=await user();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);const body=await request.json().catch(()=>null);if(!body)return json({error:"Invalid JSON"},400);const id=String(body.id||""),value=String(body.value||"").trim().slice(0,180);if(!id||!value)return json({error:"Invalid entry"},400);const rows=await sql`UPDATE public.entries SET value=${value} WHERE id=${id} AND user_id=${u.id} RETURNING id`;if(!rows.length)return json({error:"Entry not found"},404);return json({ok:true})}catch(error){console.error("entries PATCH failed",error);return json({error:"Unable to update entry"},500)}}
export async function DELETE(request:Request){try{const u=await user();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);const body=await request.json().catch(()=>({}));if(body.all){await sql`DELETE FROM public.entries WHERE user_id=${u.id}`}else if(body.id){const rows=await sql`DELETE FROM public.entries WHERE id=${String(body.id)} AND user_id=${u.id} RETURNING id`;if(!rows.length)return json({error:"Entry not found"},404)}else return json({error:"id or all is required"},400);return json({ok:true})}catch(error){console.error("entries DELETE failed",error);return json({error:"Unable to delete entry"},500)}}
