import {neon} from "@neondatabase/serverless";
import {auth} from "../../../lib/auth/server";
const sql=neon(process.env.DATABASE_URL!);
async function user(){const {user}=await auth.getSession();return user||null}
async function ensure(){await sql`CREATE TABLE IF NOT EXISTS public.entries (id text PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), user_id text NOT NULL, type text NOT NULL, value text NOT NULL, at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS entries_user_at_idx ON public.entries (user_id, at DESC)`}
export async function GET(){const u=await user();if(!u)return Response.json({entries:[]},{status:401});await ensure();const rows=await sql`SELECT id,type,value,at FROM public.entries WHERE user_id=${u.id} ORDER BY at DESC LIMIT 300`;return Response.json({entries:rows})}
export async function POST(request:Request){const u=await user();if(!u)return Response.json({error:"Unauthorized"},{status:401});await ensure();const body=await request.json();const type=String(body.type||"").slice(0,80),value=String(body.value||"").trim().slice(0,180),at=String(body.at||new Date().toISOString());if(!type||!value)return Response.json({error:"Invalid entry"},{status:400});const rows=await sql`INSERT INTO public.entries (user_id,type,value,at) VALUES (${u.id},${type},${value},${at}) RETURNING id,type,value,at`;return Response.json({entry:rows[0]},{status:201})}
export async function PATCH(request:Request){const u=await user();if(!u)return Response.json({error:"Unauthorized"},{status:401});await ensure();const body=await request.json();const id=String(body.id||""),value=String(body.value||"").trim().slice(0,180);if(!id||!value)return Response.json({error:"Invalid entry"},{status:400});await sql`UPDATE public.entries SET value=${value} WHERE id=${id} AND user_id=${u.id}`;return Response.json({ok:true})}
export async function DELETE(request:Request){const u=await user();if(!u)return Response.json({error:"Unauthorized"},{status:401});await ensure();const body=await request.json().catch(()=>({}));if(body.all){await sql`DELETE FROM public.entries WHERE user_id=${u.id}`}else if(body.id){await sql`DELETE FROM public.entries WHERE id=${String(body.id)} AND user_id=${u.id}`}return Response.json({ok:true})}

