"use client";
import {FormEvent,useState} from "react";
import {getSupabaseBrowserClient,isSupabaseConfigured} from "../../lib/supabase-browser";

export default function AuthPage(){
 const [mode,setMode]=useState<"signin"|"signup">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const ar=typeof window!=="undefined"&&localStorage.getItem("nutclue-lang")==="ar";
 const submit=async(e:FormEvent)=>{e.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase){setMessage(ar?"أضف مفاتيح Supabase أولًا من إعدادات Vercel.":"Add the Supabase keys in Vercel first.");return}setBusy(true);setMessage("");const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+"/auth/callback"}});setBusy(false);if(result.error){setMessage(result.error.message)}else if(mode==="signup"){setMessage(ar?"اتأكد من بريدك الإلكتروني ثم ارجع للتطبيق.":"Check your email, then return to NutClue.")}else location.href="/";}
 return <main className="authPage" dir={ar?"rtl":"ltr"}><section className="authCard"><a href="/" className="authBrand">NUT<span>CLUE</span></a><small>{ar?"مساحتك الخاصة":"YOUR PRIVATE SPACE"}</small><h1>{ar?"احتفظ بتفاصيلك المفيدة.":"Keep the useful details."}</h1><p>{ar?"سجّل دخولك عشان يومياتك تفضل معاك على أي جهاز.":"Sign in so your journal can follow you across devices."}</p>{!isSupabaseConfigured()&&<div className="authNotice">{ar?"قاعدة البيانات لم تُربط بعد. أضف مفاتيح Supabase في Vercel.":"Database is not connected yet. Add the Supabase keys in Vercel."}</div>}<form onSubmit={submit}><label>{ar?"البريد الإلكتروني":"Email"}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>{ar?"كلمة المرور":"Password"}<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="signin"?"current-password":"new-password"}/></label><button disabled={busy}>{busy?(ar?"جاري التنفيذ…":"Working…"):(mode==="signin"?(ar?"دخول":"Sign in"):(ar?"إنشاء حساب":"Create account"))}</button></form>{message&&<p className="authMessage" role="status">{message}</p>}<button className="authSwitch" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?(ar?"لسه جديد؟ أنشئ حسابًا":"New here? Create an account"):(ar?"عندي حساب بالفعل":"I already have an account")}</button><a className="authBack" href="/">{ar?"ارجع للموقع":"Back to NutClue"}</a></section></main>
}

