"use client";
import {useEffect,useState} from "react";
import {authClient} from "../../lib/auth/client";
const copy={
 en:{private:"YOUR PRIVATE SPACE",loginTitle:"Sign in to continue with your data.",loginP:"Your journal, learning progress and optional child profile are only visible inside your account.",login:"SIGN IN →",account:"ACCOUNT",title:"Your data, clearly.",email:"Email",journal:"journal entries",child:"optional child profile",open:"Open journal",parent:"Family space",privacy:"Privacy",manage:"Manage your data",manageP:"You can delete your journal and child profile from the database. This page does not delete the account itself.",deleting:"Deleting…",clear:"Delete journal and child profile",out:"Sign out",back:"Back to public site",confirm:"Delete your journal and child profile?",loaded:"We couldn't load your account summary.",deleted:"Your journal and child profile were deleted.",deleteFail:"We couldn't confirm deletion of all data. Please try again.",switch:"عربي"},
 ar:{private:"مساحتك الخاصة",loginTitle:"سجّل الدخول لمتابعة بياناتك.",loginP:"اليوميات والتقدم التعليمي وملف الطفل لا تظهر إلا داخل الحساب.",login:"تسجيل الدخول ←",account:"الحساب",title:"بياناتك، بشكل واضح.",email:"البريد الإلكتروني",journal:"سجل في اليوميات",child:"ملف طفل اختياري",open:"افتح اليوميات",parent:"مساحة الأهل",privacy:"الخصوصية",manage:"إدارة بياناتك",manageP:"يمكنك حذف اليوميات وملف الطفل من قاعدة البيانات. لا نحذف الحساب نفسه من هذه الصفحة.",deleting:"جارٍ الحذف…",clear:"حذف اليوميات وملف الطفل",out:"تسجيل الخروج",back:"العودة إلى الموقع العام",confirm:"هل تريد حذف يومياتك وملف الطفل؟",loaded:"تعذر تحميل ملخص الحساب.",deleted:"تم حذف اليوميات وملف الطفل.",deleteFail:"تعذر حذف البيانات الآن. لم نؤكد حذف كل البيانات؛ حاول مرة أخرى.",switch:"EN"}
};
export default function AccountPage(){
 const {data:session}=authClient.useSession();const[lang,setLang]=useState<"ar"|"en">("en");const t=copy[lang];
 const[entryCount,setEntryCount]=useState<number|null>(null),[profile,setProfile]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("ilama-bloom-lang");if(saved==="ar"||saved==="en")setLang(saved);if(!session)return;Promise.all([fetch("/api/entries").then(async r=>{if(!r.ok)throw new Error("entries");return r.json()}),fetch("/api/child-profile").then(async r=>{if(!r.ok)throw new Error("profile");return r.json()})]).then(([entries,child])=>{setEntryCount(Array.isArray(entries?.entries)?entries.entries.length:0);setProfile(child?.profiles?.[0]||null)}).catch(()=>setMessage(copy[saved==="ar"?"ar":"en"].loaded))},[session]);
 const toggle=()=>{const n=lang==="en"?"ar":"en";setLang(n);localStorage.setItem("ilama-bloom-lang",n)};
 const clearData=async()=>{if(!confirm(t.confirm))return;setBusy(true);setMessage("");try{const[entriesResponse,profileResponse]=await Promise.all([fetch("/api/entries",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({all:true})}),fetch("/api/child-profile",{method:"DELETE"})]);if(!entriesResponse.ok||!profileResponse.ok)throw new Error("delete_failed");setEntryCount(0);setProfile(null);setMessage(t.deleted)}catch{setMessage(t.deleteFail)}finally{setBusy(false)}};
 const top=<div className="privacyTop"><a href="/" className="authBrand">ILAMA <span>BLOOM</span></a><button type="button" className="authLang" onClick={toggle}>{t.switch}</button></div>;
 if(!session)return <main className="accountPage" dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="accountCard">{top}<small>{t.private}</small><h1>{t.loginTitle}</h1><p>{t.loginP}</p><a className="accountPrimary" href="/auth/sign-in?next=%2Faccount">{t.login}</a></section></main>;
 return <main className="accountPage" dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="accountCard">{top}<small>{t.account}</small><h1>{t.title}</h1><div className="accountIdentity"><span>{t.email}</span><b>{session.user.email}</b></div><div className="accountStats"><div><b>{entryCount===null?"…":entryCount}</b><span>{t.journal}</span></div><div><b>{profile?"1":"0"}</b><span>{t.child}</span></div></div><div className="accountLinks"><a href="/#/journal">{t.open}</a><a href="/parent">{t.parent}</a><a href="/privacy">{t.privacy}</a></div><div className="accountDanger"><b>{t.manage}</b><p>{t.manageP}</p><button type="button" disabled={busy} onClick={clearData}>{busy?t.deleting:t.clear}</button></div><p className="accountMessage" role="status">{message}</p><button type="button" className="accountSignOut" onClick={async()=>{setBusy(true);try{await authClient.signOut();window.location.replace("/")}catch{setBusy(false);setMessage(t.deleteFail)}}}>{t.out}</button><a className="accountBack" href="/">{t.back}</a></section></main>
}
