"use client";
import {useEffect,useState} from "react";
import {authClient} from "../../lib/auth/client";

export default function AccountPage(){
 const {data:session}=authClient.useSession();
 const [entryCount,setEntryCount]=useState<number|null>(null),[profile,setProfile]=useState<any>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!session)return;Promise.all([fetch("/api/entries").then(r=>r.ok?r.json():null),fetch("/api/child-profile").then(r=>r.ok?r.json():null)]).then(([entries,child])=>{setEntryCount(Array.isArray(entries?.entries)?entries.entries.length:0);setProfile(child?.profiles?.[0]||null)}).catch(()=>setMessage("تعذر تحميل ملخص الحساب."))},[session]);
 const clearData=async()=>{if(!confirm("هل تريد حذف يومياتك وملف الطفل؟"))return;setBusy(true);setMessage("");try{await Promise.all([fetch("/api/entries",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({all:true})}),fetch("/api/child-profile",{method:"DELETE"})]);setEntryCount(0);setProfile(null);setMessage("تم حذف اليوميات وملف الطفل.")}catch{setMessage("تعذر حذف البيانات الآن.")}finally{setBusy(false)}};
 if(!session)return <main className="accountPage" dir="rtl" lang="ar"><section className="accountCard"><a href="/" className="authBrand">NUT<span>CLUE</span></a><small>مساحتك الخاصة</small><h1>سجّل الدخول لمتابعة بياناتك.</h1><p>اليوميات والتقدم التعليمي وملف الطفل لا تظهر إلا داخل الحساب.</p><a className="accountPrimary" href="/auth/sign-in?next=%2Faccount">تسجيل الدخول ←</a></section></main>;
 return <main className="accountPage" dir="rtl" lang="ar"><section className="accountCard"><a href="/" className="authBrand">NUT<span>CLUE</span></a><small>الحساب</small><h1>بياناتك، بشكل واضح.</h1><div className="accountIdentity"><span>البريد الإلكتروني</span><b>{session.user.email}</b></div><div className="accountStats"><div><b>{entryCount===null?"…":entryCount}</b><span>سجل في اليوميات</span></div><div><b>{profile?"1":"0"}</b><span>ملف طفل اختياري</span></div></div><div className="accountLinks"><a href="/#/journal">افتح اليوميات</a><a href="/parent">مساحة الأهل</a><a href="/privacy">الخصوصية</a></div><div className="accountDanger"><b>إدارة بياناتك</b><p>يمكنك حذف اليوميات وملف الطفل من قاعدة البيانات. لا نحذف الحساب نفسه من هذه الصفحة.</p><button disabled={busy} onClick={clearData}>{busy?"جارٍ الحذف…":"حذف اليوميات وملف الطفل"}</button></div><p className="accountMessage" role="status">{message}</p><button className="accountSignOut" onClick={async()=>{await authClient.signOut();window.location.replace("/")}}>تسجيل الخروج</button><a className="accountBack" href="/">العودة إلى الموقع العام</a></section></main>}
