"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./EditorialPages.module.css";

export type View="home"|"learn"|"kids"|"everyday"|"lens"|"atlas"|"log"|"journal"|"visit"|"about"|"privacy"|"sitemap";
export type Entry={id?:string;type:string;value:string;at:string};
const labels:{[k:string]:string}={Meal:"وجبة",Water:"مياه",Sleep:"نوم",Medication:"دواء","Work / activity":"نشاط / شغل",Smoking:"تدخين",Condition:"حالة صحية","Previous operation":"عملية سابقة",Feeling:"إحساس",Measurement:"قياس",Note:"ملاحظة","Question for visit":"سؤال للزيارة","Food label":"بطاقة طعام",Food:"أكل"};
const Hero=({kicker,title,italic,copy,img}:{kicker:string;title:string;italic?:string;copy:string;img:string})=><section className={styles.hero}><div><p className={styles.kicker}>{kicker}</p><h1>{title}{italic&&<><br/><em>{italic}</em></>}</h1><p>{copy}</p></div><figure><img src={img} alt=""/></figure></section>;
const Arrow=()=> <span aria-hidden="true">→</span>;

export function LearnEditorial({go,ar}:{go:(v:View)=>void;ar:boolean}){
 type Guide={id:string;eyebrow_en:string;eyebrow_ar:string;title_en:string;title_ar:string;body_en:string;body_ar:string;practical_en:string;practical_ar:string};
 const [q,setQ]=useState(""),[active,setActive]=useState<string|null>(null),[db,setDb]=useState<Guide[]>([]);
 useEffect(()=>{fetch("/api/learning-guides").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.guides)&&setDb(d.guides)).catch(()=>{})},[]);
 const fallback:Guide[]=[{id:"carbs",eyebrow_en:"CARBOHYDRATES",eyebrow_ar:"الكربوهيدرات",title_en:"Carbohydrates, without the drama.",title_ar:"الكربوهيدرات من غير تعقيد.",body_en:"Start with what the food contains and the portion.",body_ar:"ابدأ بمكونات الأكل والكمية.",practical_en:"Bread, rice, fruit, milk and legumes can contribute carbohydrate.",practical_ar:"العيش والأرز والفاكهة واللبن والبقوليات ممكن تضيف كربوهيدرات."}];
 const guides=(db.length?db:fallback).map(g=>({id:g.id,eye:ar?g.eyebrow_ar:g.eyebrow_en,title:ar?g.title_ar:g.title_en,body:ar?g.body_ar:g.body_en,practical:ar?g.practical_ar:g.practical_en})); const needle=q.toLowerCase().trim(); const shown=guides.filter(g=>!needle||Object.values(g).join(" ").toLowerCase().includes(needle));
 return <div className={styles.page}><Hero kicker={ar?"التغذية · المكتبة":"NUTRITION · LIBRARY"} title={ar?"المعرفة التي":"Knowledge that"} italic={ar?"تخدم يومك.":"serves real life."} copy={ar?"ابحث في موضوعات التغذية والصحة بلغة واضحة، ثم افتح ما تحتاجه فقط.":"Explore nutrition and health in plain language, then open only what you need."} img="https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.library}><div className={styles.search}><label>{ar?"ابحث في المكتبة":"SEARCH THE LIBRARY"}</label><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"كربوهيدرات، طعام، تحاليل...":"Carbs, food, labs..."}/>{q&&<button onClick={()=>setQ("")}>×</button>}</div></div><div className={styles.guideGrid}>{shown.map((g,i)=><article key={g.id}><span>0{i+1}</span><p className={styles.kicker}>{g.eye}</p><h2>{g.title}</h2><p>{g.body}</p>{active===g.id&&<aside><b>{ar?"بشكل عملي":"MAKE IT PRACTICAL"}</b><p>{g.practical}</p></aside>}<button onClick={()=>setActive(active===g.id?null:g.id)}>{active===g.id?(ar?"إغلاق":"Close"):(ar?"اقرأ الدليل":"Read guide")} <Arrow/></button></article>)}</div><div className={styles.bridge}><div><p className={styles.kicker}>{ar?"من المعرفة للتطبيق":"FROM KNOWLEDGE TO CONTEXT"}</p><h2>{ar?"احتفظ بما يهمك.":"Keep what matters."}</h2></div><button onClick={()=>go("log")}>{ar?"أضف لليوميات":"Add to journal"} <Arrow/></button></div></section></div>
}

export function LensEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:View)=>void;ar:boolean}){
 const [serving,setServing]=useState("30"),[carbs,setCarbs]=useState(""),[basis,setBasis]=useState("100"),[saved,setSaved]=useState(false);
 const result=useMemo(()=>{const a=Number(carbs),b=Number(serving),c=Number(basis);return carbs&&serving&&basis&&a>=0&&b>0&&c>0?a*b/c:null},[carbs,serving,basis]);
 return <div className={styles.page}><Hero kicker={ar?"عدسة الطعام":"FOOD LENS"} title={ar?"اقرأ البطاقة":"Read the label."} italic={ar?"احسب حصتك.":"Know your portion."} copy={ar?"حساب بسيط من الأرقام المكتوبة على العبوة — بدون تخمين أو قرارات علاجية.":"Simple portion arithmetic from the numbers on the pack — no guessing, no treatment decisions."} img="https://images.pexels.com/photos/7262897/pexels-photo-7262897.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.toolSplit}><div className={styles.formCard}><p className={styles.kicker}>01 · {ar?"بيانات البطاقة":"LABEL"}</p><label>{ar?"إجمالي الكربوهيدرات":"Total carbohydrate"}<span><input inputMode="decimal" value={carbs} onChange={e=>{setCarbs(e.target.value);setSaved(false)}} placeholder="68"/><i>g</i></span></label><label>{ar?"الكمية المرجعية":"Label basis"}<span><input inputMode="decimal" value={basis} onChange={e=>{setBasis(e.target.value);setSaved(false)}}/><i>g</i></span></label><p className={styles.kicker}>02 · {ar?"حصتك":"YOUR PORTION"}</p><label>{ar?"الكمية":"Portion"}<span><input inputMode="decimal" value={serving} onChange={e=>{setServing(e.target.value);setSaved(false)}}/><i>g</i></span></label></div><aside className={styles.result}><p className={styles.kicker}>{ar?"لهذه الحصة":"FOR THIS PORTION"}</p><strong>{result===null?"—":result.toFixed(1)}<i>{result===null?"":"g"}</i></strong><h2>{ar?"كربوهيدرات":"carbohydrate"}</h2>{result!==null&&<><p>{carbs} g × {serving} g ÷ {basis} g</p><button onClick={async()=>{const ok=await add("Food label",`Label: ${carbs} g carbohydrate per ${basis} g; portion ${serving} g ≈ ${result.toFixed(1)} g carbohydrate`);setSaved(Boolean(ok))}}>{saved?(ar?"✓ تم الحفظ":"✓ Saved"):(ar?"احفظ في اليوميات":"Remember this")} <Arrow/></button></>}<button className={styles.textBtn} onClick={()=>go("atlas")}>{ar?"اذهب لأطلس الطعام":"Explore Food Atlas"} <Arrow/></button></aside></section></div>
}

export function LogEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:View)=>void;ar:boolean}){
 const [type,setType]=useState("Meal"),[value,setValue]=useState(""); const types=[["Meal","Meal"],["Water","Water"],["Sleep","Sleep"],["Medication","Medication"],["Work / activity","Activity"],["Feeling","Feeling"],["Measurement","Measurement"],["Note","Note"]];
 return <div className={styles.page}><Hero kicker={ar?"سجل سريع":"QUICK LOG"} title={ar?"لحظة واحدة.":"One moment."} italic={ar?"احتفظ بها.":"Worth remembering."} copy={ar?"اختار النوع، اكتب ما يهمك، واحفظه في يومياتك.":"Choose a category, write what matters, and keep it in your journal."} img="https://images.pexels.com/photos/4050990/pexels-photo-4050990.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.logPanel}><p className={styles.kicker}>01 · {ar?"اختر النوع":"CHOOSE A CATEGORY"}</p><div className={styles.typeRow}>{types.map(([key,name])=><button className={type===key?styles.active:""} key={key} onClick={()=>setType(key)}>{ar?(labels[key]||key):name}</button>)}</div><label className={styles.noteField}><span>02 · {ar?"اكتب ما تريد تذكره":"WRITE WHAT YOU WANT TO REMEMBER"}</span><textarea maxLength={180} value={value} onChange={e=>setValue(e.target.value)} placeholder={ar?"تفصيلة قصيرة تكفي...":"A short note is enough..."}/><small>{value.length}/180</small></label><div className={styles.actions}><button className={styles.textBtn} onClick={()=>go("journal")}>{ar?"إلغاء":"Cancel"}</button><button disabled={!value.trim()} onClick={async()=>{if(await add(type,value.trim())){setValue("");go("journal")}}}>{ar?"احفظ في اليوميات":"Save to journal"} <Arrow/></button></div></section></div>
}

export function JournalEditorial({entries,go,clearEntries,removeEntry,updateEntry,undoEntry,undoRemove,ar}:{entries:Entry[];go:(v:View)=>void;clearEntries:()=>void;removeEntry:(at:string)=>void;updateEntry:(at:string,value:string)=>void;undoEntry:Entry|null;undoRemove:()=>void;ar:boolean}){
 const [editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(""),[filter,setFilter]=useState("All"); const types=["All",...Array.from(new Set(entries.map(e=>e.type)))]; const shown=filter==="All"?entries:entries.filter(e=>e.type===filter);
 return <div className={styles.page}><Hero kicker={ar?"اليوميات":"YOUR JOURNAL"} title={ar?"يومك،":"Your day,"} italic={ar?"بوضوح وهدوء.":"without the paperwork."} copy={ar?"خط زمني بسيط للحاجات التي اخترت الاحتفاظ بها.":"A calm timeline of what you chose to remember."} img="https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.journal}>{undoEntry&&<div className={styles.notice}>{ar?"تم حذف السجل.":"Entry deleted."}<button onClick={undoRemove}>{ar?"تراجع":"Undo"}</button></div>}<div className={styles.journalTop}><div className={styles.filters}>{types.map(t=><button className={filter===t?styles.active:""} onClick={()=>setFilter(t)} key={t}>{ar?(t==="All"?"الكل":labels[t]||t):t}</button>)}</div><button onClick={()=>go("log")}>{ar?"+ سجل جديد":"+ New entry"}</button></div>{!shown.length?<div className={styles.empty}><p className={styles.kicker}>{ar?"مساحة هادئة":"A QUIET SPACE"}</p><h2>{ar?"لا توجد سجلات هنا بعد.":"Nothing here yet."}</h2><p>{ar?"أضف فقط ما يستحق أن ترجع إليه.":"Add only what feels worth returning to."}</p></div>:<div className={styles.timeline}>{shown.map(e=><article key={e.at}><time>{new Date(e.at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}<small>{new Date(e.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></time><div><p className={styles.kicker}>{ar?(labels[e.type]||e.type):e.type}</p>{editing===e.at?<><textarea value={draft} maxLength={180} onChange={x=>setDraft(x.target.value)}/><div className={styles.inlineActions}><button onClick={()=>setEditing(null)}>{ar?"إلغاء":"Cancel"}</button><button onClick={()=>{updateEntry(e.at,draft);setEditing(null)}}>{ar?"حفظ":"Save"}</button></div></>:<h3>{e.value}</h3>}</div>{editing!==e.at&&<div className={styles.inlineActions}><button onClick={()=>{setEditing(e.at);setDraft(e.value)}}>{ar?"تعديل":"Edit"}</button><button onClick={()=>removeEntry(e.at)}>×</button></div>}</article>)}</div>} {entries.length>0&&<button className={styles.clear} onClick={clearEntries}>{ar?"مسح اليوميات":"Clear journal"}</button>}</section></div>
}

export function VisitEditorial({entries,add,ar}:{entries:Entry[];add:(t:string,v:string)=>Promise<boolean>|boolean;ar:boolean}){
 const [days,setDays]=useState(7),[question,setQuestion]=useState(""),[copied,setCopied]=useState(false); const recent=useMemo(()=>entries.filter(e=>Date.now()-new Date(e.at).getTime()<days*86400000),[entries,days]); const questions=recent.filter(e=>e.type==="Question for visit"), context=recent.filter(e=>e.type!=="Question for visit");
 const copy=async()=>{const txt=[ar?"ILAMA BLOOM — ملخص الزيارة":"ILAMA BLOOM — visit summary",...context.map(e=>`${new Date(e.at).toLocaleDateString()}: ${ar?(labels[e.type]||e.type):e.type} — ${e.value}`),...questions.map(e=>`? ${e.value}`)].join("\n");try{await navigator.clipboard.writeText(txt);setCopied(true)}catch{}};
 return <div className={styles.page}><Hero kicker={ar?"تجهيز الزيارة":"VISIT PREP"} title={ar?"خذ معك السياق،":"Bring context,"} italic={ar?"لا اختبارًا للذاكرة.":"not a memory test."} copy={ar?"ملخص مرتب مبني فقط على ما سجلته أنت.":"A compact, organized summary made only from what you recorded."} img="https://images.pexels.com/photos/3786157/pexels-photo-3786157.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.visit}><div className={styles.range}><p className={styles.kicker}>{ar?"الفترة":"TIME WINDOW"}</p>{[7,14,30].map(n=><button className={days===n?styles.active:""} onClick={()=>setDays(n)} key={n}>{n} {ar?"يوم":"days"}</button>)}</div><div className={styles.stats}><span><small>{ar?"السجلات":"ENTRIES"}</small><b>{recent.length}</b></span><span><small>{ar?"الأسئلة":"QUESTIONS"}</small><b>{questions.length}</b></span><button onClick={copy}>{copied?(ar?"✓ تم النسخ":"✓ Copied"):(ar?"انسخ الملخص":"Copy summary")} <Arrow/></button></div><div className={styles.visitGrid}><div><p className={styles.kicker}>{ar?"السياق الأخير":"RECENT CONTEXT"}</p>{context.length?context.slice(0,15).map(e=><article key={e.at}><b>{ar?(labels[e.type]||e.type):e.type}</b><p>{e.value}</p><small>{new Date(e.at).toLocaleDateString()}</small></article>):<div className={styles.empty}><h2>{ar?"لا توجد سجلات في هذه الفترة.":"No entries in this period."}</h2></div>}</div><aside><p className={styles.kicker}>{ar?"جيب الأسئلة":"QUESTION POCKET"}</p><h2>{ar?"احفظ السؤال قبل أن تنساه.":"Save it before you forget it."}</h2><textarea value={question} maxLength={180} onChange={e=>setQuestion(e.target.value)} placeholder={ar?"ماذا أريد أن أسأل؟":"What do I want to ask?"}/><button disabled={!question.trim()} onClick={async()=>{if(await add("Question for visit",question.trim()))setQuestion("")}}>{ar?"احفظ السؤال":"Save question"} <Arrow/></button>{questions.map(q=><p className={styles.savedQ} key={q.at}>? {q.value}</p>)}</aside></div></section></div>
}

export function AboutEditorial({ar}:{ar:boolean}){return <div className={styles.page}><Hero kicker={ar?"عن إيلاما بلوم":"ABOUT ILAMA BLOOM"} title={ar?"معلومات صحية،":"Health information,"} italic={ar?"بلغة إنسانية.":"made human."} copy={ar?"فكرة بسيطة: المعرفة الغذائية والصحية اليومية يجب أن تكون أسهل في الفهم والتذكر والنقاش الحقيقي.":"A simple idea: everyday nutrition and health information should be easier to understand, remember and bring into real conversations."} img="https://images.pexels.com/photos/5945652/pexels-photo-5945652.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.about}><div><p className={styles.kicker}>{ar?"فلسفتنا":"OUR PHILOSOPHY"}</p><h2>{ar?"افهم · تذكّر · ناقش":"Understand · Remember · Discuss"}</h2><p>{ar?"إيلاما بلوم يضع الطعام والجسد والسياق في صورة واحدة، بعيدًا عن ثقافة الدايت والأحكام والتعقيد غير الضروري.":"ILAMA BLOOM brings food, body and context into one picture — away from diet culture, judgement and unnecessary complexity."}</p></div><aside><p className={styles.kicker}>{ar?"الصوت الطبي":"CLINICAL VOICE"}</p><h3>{ar?"د. دينا حسن":"Dr. Dina Hassan"}</h3><b>{ar?"طب الأطفال · التغذية العلاجية":"Pediatrics · Clinical Nutrition"}</b><p>MRCPCH · Final examination September 2026 · result pending</p><p>{ar?"دبلومة التغذية العلاجية · NNI":"Diploma in Clinical Nutrition · NNI"}</p></aside></section></div>}

export function PrivacyEditorial({ar}:{ar:boolean}){const rows=ar?[["01","ما الذي نحفظه","بيانات الملف الشخصي التي تختار إضافتها، وسجلات اليوميات، وتقدم الألعاب المدعوم يمكن حفظها مع حسابك."],["02","تحكمك","يمكنك تعديل سجلات اليوميات أو حذفها أو مسحها، وتعديل ملفك الشخصي من مساحة My ILAMA."],["03","الحجز","عند فتح Calendly من My ILAMA، يتم تمرير الاسم والبريد الإلكتروني فقط للتعبئة المسبقة. لا نرسل السياق الصحي إلى Calendly."],["04","الغرض","المعلومات التعليمية وأدوات التسجيل لا تستبدل التقييم أو التشخيص أو العلاج الطبي."]]:[["01","What we store","Profile information you choose to add, journal entries and supported game progress can be stored with your account."],["02","Your control","You can edit or delete journal entries, clear them, and update your profile from My ILAMA."],["03","Booking","When Calendly opens inside My ILAMA, only your name and email are passed for prefilling. Health context is not sent to Calendly."],["04","Purpose","Educational information and tracking tools do not replace medical assessment, diagnosis or treatment."]];return <div className={styles.page}><Hero kicker={ar?"الخصوصية":"PRIVACY"} title={ar?"بياناتك،":"Your data,"} italic={ar?"بوضوح.":"clearly."} copy={ar?"نستخدم بيانات الحساب واليوميات فقط لتقديم الخصائص التي تختار استخدامها.":"We use account and journal data to provide the features you choose to use."} img="https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=1600"/><section className={styles.policy}>{rows.map(([n,t,c])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{c}</p></article>)}</section></div>}

export function SitemapEditorial({go,ar}:{go:(v:View)=>void;ar:boolean}){const links:(readonly [string,string,View])[]=[ar?["التغذية","المكتبة والأدلة","learn"]:["Nutrition","Library & guides","learn"],ar?["الأطفال","التعلم والألعاب","kids"]:["Kids","Learning & games","kids"],ar?["أطلس الطعام","الأطعمة والحصص","atlas"]:["Food Atlas","Foods & portions","atlas"],ar?["الحياة اليومية","مصر · الميزانية · المراهقون","everyday"]:["Everyday","Egypt · budget · teens","everyday"],ar?["عدسة الطعام","حساب البطاقة","lens"]:["Food Lens","Label calculator","lens"],ar?["اليوميات","سجلاتك الخاصة","journal"]:["Journal","Your private notes","journal"],ar?["تجهيز الزيارة","السياق والأسئلة","visit"]:["Visit Prep","Context & questions","visit"],ar?["عن إيلاما","الفكرة والفلسفة","about"]:["About","Idea & philosophy","about"]];return <div className={styles.page}><Hero kicker={ar?"خريطة الموقع":"SITE MAP"} title={ar?"كل شيء،":"Everything,"} italic={ar?"سهل الوصول.":"easy to find."} copy={ar?"اذهب مباشرة إلى أي مساحة داخل إيلاما بلوم.":"Jump directly to any space inside ILAMA BLOOM."} img="https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=1600"/><section className={styles.mapGrid}>{links.map(([t,c,v],i)=><button key={t} onClick={()=>go(v)}><span>0{i+1}</span><h2>{t}</h2><p>{c}</p><Arrow/></button>)}</section></div>}
