"use client";
import {useMemo,useState} from "react";
import styles from "./EverydayEditorial.module.css";
type Props={ar:boolean;add:(t:string,v:string)=>Promise<boolean>|boolean};
const modes=[["Normal","يوم عادي"],["Busy","يوم مشغول"],["Work","شغل"],["Travel","سفر"],["Exam","امتحانات"],["Training","تمرين"],["Sick","تعبان"],["Recovery","تعافي"],["Family","عائلة"],["Ramadan","رمضان"],["Shift Work","ورديات"],["New Parent","أب/أم جديد"],["Vacation","إجازة"]];
const proteins=[["Eggs","بيض"],["Foul","فول"],["Lentils","عدس"],["Chickpeas","حمص"],["Yogurt","زبادي"],["Sardines","سردين"]];
const bases=[["Baladi bread","عيش بلدي"],["Rice","أرز"],["Potatoes","بطاطس"],["Pasta","مكرونة"]];
const veg=[["Tomato + cucumber","طماطم + خيار"],["Seasonal vegetables","خضار موسمي"],["Molokhia","ملوخية"],["Mixed salad","سلطة مشكلة"]];
const feelings=[["Calm","هادي"],["Okay","تمام"],["Tired","مرهق"],["Stressed","مضغوط"],["Low","طاقتي قليلة"]];
export default function EverydayEditorial({ar,add}:Props){
 const[mode,setMode]=useState("Normal"),[budget,setBudget]=useState("60"),[protein,setProtein]=useState(0),[base,setBase]=useState(0),[vegetable,setVegetable]=useState(0),[saved,setSaved]=useState("");
 const[steps,setSteps]=useState(""),[move,setMove]=useState(""),[water,setWater]=useState(""),[sleep,setSleep]=useState(""),[energy,setEnergy]=useState(3),[feeling,setFeeling]=useState("Okay"),[teenMode,setTeenMode]=useState("Study");
 const amount=Math.max(0,Number(budget)||0); const band=amount<40?(ar?"اعتمد على البقول + العيش أو النشويات المتاحة":"Build around legumes + the staple you already have"):amount<90?(ar?"وجبة بسيطة ومتوازنة من مكونات يومية":"A simple balanced meal from everyday ingredients"):(ar?"عندك مساحة أكبر للتنوع؛ لا تحتاج منتجات خاصة":"More room for variety; no special products required");
 const meal=useMemo(()=>[proteins[protein][ar?1:0],bases[base][ar?1:0],veg[vegetable][ar?1:0]].join(" · "),[protein,base,vegetable,ar]);
 const save=async(type:string,value:string)=>{const ok=await add(type,value);if(ok){setSaved(type);setTimeout(()=>setSaved(""),1800)}return ok};
 const saveRhythm=async()=>{const items:[[string,string]]|[string,string][]=[];if(steps)items.push(["Steps",steps]);if(move)items.push(["Move",move+" min"]);if(water)items.push(["Water",water+" glasses"]);if(sleep)items.push(["Sleep",sleep+" h"]);items.push(["Energy",String(energy)+"/5"],["Feeling",feeling]);let ok=true;for(const [t,v] of items)ok=(await save(t,v))&&ok;if(ok){setSaved("rhythm");setTimeout(()=>setSaved(""),1800)}};
 return <div className={styles.page}><section className={styles.hero}><div><p>EVERYDAY ILAMA · EGYPT</p><h1>{ar?"الصحة في الحياة":"Health that fits"}<br/><em>{ar?"الحقيقية.":"real life."}</em></h1><span>{ar?"ميزانية، وقت، شغل، دراسة، سفر، رمضان — السياق جزء من الخطة.":"Budget, time, work, study, travel and Ramadan — context belongs in the plan."}</span></div><figure><img src="https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=1600" alt=""/></figure></section>
 <section className={styles.modes}><header><small>01 · LIFE MODE</small><h2>{ar?"إيه شكل يومك النهارده؟":"What kind of day is this?"}</h2><p>{ar?"اختيار السياق لا يحكم عليك؛ هو فقط يجعل يومياتك أذكى.":"Context is not a score. It simply makes your journal more useful."}</p></header><div>{modes.map(([en,arx])=><button className={mode===en?styles.on:""} onClick={()=>setMode(en)} key={en}>{ar?arx:en}</button>)}</div><button className={styles.save} onClick={()=>save("Life mode",mode)}>{saved==="Life mode"?(ar?"✓ اتحفظ":"✓ Saved"):(ar?"احفظ سياق اليوم":"Save today's context")}</button></section>
 <section className={styles.rhythm}><div className={styles.rhythmIntro}><small>02 · MY DAY</small><h2>{ar?"شوف يومك،":"See your day,"}<br/><em>{ar?"من غير درجات.":"without a score."}</em></h2><p>{ar?"سجّل اللي يهمك فقط. مفيش هدف إجباري ولا يوم فاشل.":"Log only what matters to you. There is no compulsory target and no failed day."}</p></div><div className={styles.rhythmGrid}><Metric label={ar?"الخطوات":"STEPS"} value={steps} set={setSteps} unit={ar?"خطوة":"steps"} placeholder="4200"/><Metric label={ar?"دقائق الحركة":"MOVE MINUTES"} value={move} set={setMove} unit={ar?"دقيقة":"min"} placeholder="20"/><Metric label={ar?"المياه":"WATER"} value={water} set={setWater} unit={ar?"كوب":"glasses"} placeholder="6"/><Metric label={ar?"النوم":"SLEEP"} value={sleep} set={setSleep} unit={ar?"ساعة":"hours"} placeholder="7.5" decimal/><div className={styles.signal}><b>{ar?"الطاقة":"ENERGY"}</b><div className={styles.scale}>{[1,2,3,4,5].map(n=><button className={energy===n?styles.hit:""} key={n} onClick={()=>setEnergy(n)}>{n}</button>)}</div><span>{ar?"ملاحظة شخصية، مش تقييم صحي.":"A personal signal, not a health score."}</span></div><div className={styles.signal}><b>{ar?"إحساسك":"FEELING"}</b><div className={styles.feelings}>{feelings.map(([en,ara])=><button className={feeling===en?styles.hit:""} key={en} onClick={()=>setFeeling(en)}>{ar?ara:en}</button>)}</div></div><button className={styles.rhythmSave} onClick={saveRhythm}>{saved==="rhythm"?(ar?"✓ اليوم اتحفظ":"✓ Day saved"):(ar?"احفظ إشارات اليوم":"Save today's signals")}</button></div></section>
 <section className={styles.budget}><div className={styles.budgetCopy}><small>03 · BUDGET MEAL LAB</small><h2>{ar?"ابدأ بما عندك،":"Start with what you have,"}<br/><em>{ar?"مش بما ينقصك.":"not what you're missing."}</em></h2><p>{band}</p><label>{ar?"ميزانية تقريبية للفرد (جنيه)":"Approx. budget per person (EGP)"}<input inputMode="numeric" value={budget} onChange={e=>setBudget(e.target.value.replace(/[^0-9]/g,"").slice(0,4))}/></label></div><div className={styles.builder}><Picker n="PROTEIN" items={proteins} value={protein} set={setProtein} ar={ar}/><Picker n="STAPLE" items={bases} value={base} set={setBase} ar={ar}/><Picker n="VEGETABLE" items={veg} value={vegetable} set={setVegetable} ar={ar}/><aside><small>{ar?"وجبتك":"YOUR MEAL"}</small><strong>{meal}</strong><p>{ar?"اقتراح للتفكير والتنويع، وليس تسعيرًا لحظيًا أو وصفة علاجية.":"A practical composition prompt, not live pricing or a treatment plan."}</p><button onClick={()=>save("Meal",meal)}>{saved==="Meal"?(ar?"✓ في اليوميات":"✓ In journal"):(ar?"احفظ الوجبة":"Remember meal")}</button></aside></div></section>
 <section className={styles.teens}><div><small>04 · TEENS</small><h2>{ar?"مش دايت.":"Not a diet."}<br/><em>{ar?"مش محاضرة.":"Not a lecture."}</em></h2><p>{ar?"اختار سياقك؛ النصيحة تتغير حسب اليوم، مش حسب شكل جسمك.":"Choose your context. The prompt changes with the day, not body size."}</p><div className={styles.teenModes}>{[["Study","مذاكرة"],["Exam","امتحانات"],["Gaming","جيمينج"],["Sport","رياضة"],["Going out","خروج"]].map(([en,ara])=><button className={teenMode===en?styles.teenOn:""} onClick={()=>setTeenMode(en)} key={en}>{ar?ara:en}</button>)}</div></div><div className={styles.teenGrid}><article><b>{ar?"جرّب دلوقتي":"TRY NOW"}</b><h3>{teenMode==="Study"?(ar?"مذاكرة + طاقة":"Study + energy"):teenMode==="Exam"?(ar?"امتحان + نوم":"Exam + sleep"):teenMode==="Gaming"?(ar?"شاشة + حركة":"Screen + movement"):teenMode==="Sport"?(ar?"رياضة + وقود":"Sport + fuel"):(ar?"خروج + أكل اجتماعي":"Going out + social food")}</h3><p>{teenMode==="Study"?(ar?"قبل ما تزود كافيين، راجع نومك ومياهك ووجبتك الأخيرة.":"Before adding caffeine, notice sleep, water and your last meal."):teenMode==="Exam"?(ar?"ليلة واحدة مثالية مش الهدف؛ حاول تحافظ على وقت نوم واقعي ومتكرر.":"One perfect night is not the goal; aim for a realistic repeatable sleep window."):teenMode==="Gaming"?(ar?"اربط نهاية جولة أو مباراة بوقفة حركة قصيرة بدل الاعتماد على الإرادة.":"Tie a short movement break to the end of a round instead of relying on willpower."):teenMode==="Sport"?(ar?"سجّل كيف كان إحساسك قبل وبعد التدريب، مع الأكل والمياه كسياق.":"Notice how training felt before and after, with food and water as context."):(ar?"استمتع بالأكل مع أصحابك وسجّل اللي لاحظته لو حابب؛ مفيش تعويض أو عقاب.":"Enjoy eating with friends; log what you noticed if useful. No compensation or punishment.")}</p><button onClick={()=>save("Teen context",teenMode)}>{saved==="Teen context"?(ar?"✓ اتحفظ":"✓ Saved"):(ar?"احفظ السياق":"Remember context")}</button></article><article><b>{ar?"تجربة صغيرة":"TINY EXPERIMENT"}</b><p>{ar?"غيّر حاجة واحدة لأيام قليلة وسجل ملاحظتك بدل ما تقلب حياتك كلها مرة واحدة.":"Change one thing for a few days and notice what happens instead of overhauling everything."}</p></article></div></section></div>
}
function Metric({label,value,set,unit,placeholder,decimal=false}:{label:string;value:string;set:(v:string)=>void;unit:string;placeholder:string;decimal?:boolean}){return <label className={styles.metric}><b>{label}</b><div><input inputMode={decimal?"decimal":"numeric"} placeholder={placeholder} value={value} onChange={e=>set(e.target.value.replace(decimal?/[^0-9.]/g:/[^0-9]/g,"").slice(0,6))}/><span>{unit}</span></div></label>}
function Picker({n,items,value,set,ar}:{n:string;items:string[][];value:number;set:(n:number)=>void;ar:boolean}){return <div className={styles.picker}><small>{n}</small>{items.map((x,i)=><button className={value===i?styles.selected:""} onClick={()=>set(i)} key={x[0]}>{ar?x[1]:x[0]}</button>)}</div>}
