"use client";
import {useMemo,useState} from "react";
import styles from "./EverydayEditorial.module.css";
type Props={ar:boolean;add:(t:string,v:string)=>Promise<boolean>|boolean};
const modes=[["Normal","يوم عادي"],["Busy","يوم مشغول"],["Work","شغل"],["Travel","سفر"],["Exam","امتحانات"],["Training","تمرين"],["Recovery","تعافي"],["Ramadan","رمضان"],["Shift Work","ورديات"]];
const proteins=[["Eggs","بيض"],["Foul","فول"],["Lentils","عدس"],["Chickpeas","حمص"],["Yogurt","زبادي"],["Sardines","سردين"]];
const bases=[["Baladi bread","عيش بلدي"],["Rice","أرز"],["Potatoes","بطاطس"],["Pasta","مكرونة"]];
const veg=[["Tomato + cucumber","طماطم + خيار"],["Seasonal vegetables","خضار موسمي"],["Molokhia","ملوخية"],["Mixed salad","سلطة مشكلة"]];
export default function EverydayEditorial({ar,add}:Props){
 const[mode,setMode]=useState("Normal"),[budget,setBudget]=useState("60"),[protein,setProtein]=useState(0),[base,setBase]=useState(0),[vegetable,setVegetable]=useState(0),[saved,setSaved]=useState("");
 const amount=Math.max(0,Number(budget)||0); const band=amount<40?(ar?"اعتمد على البقول + العيش/النشويات المتاحة":"Build around legumes + the staple you already have"):amount<90?(ar?"وجبة بسيطة ومتوازنة من مكونات يومية":"A simple balanced meal from everyday ingredients"):(ar?"عندك مساحة أكبر للتنوع؛ لا تحتاج منتجات خاصة":"More room for variety; no special products required");
 const meal=useMemo(()=>[proteins[protein][ar?1:0],bases[base][ar?1:0],veg[vegetable][ar?1:0]].join(" · "),[protein,base,vegetable,ar]);
 const save=async(type:string,value:string)=>{const ok=await add(type,value);if(ok){setSaved(type);setTimeout(()=>setSaved(""),1800)}};
 return <div className={styles.page}><section className={styles.hero}><div><p>EVERYDAY ILAMA · EGYPT</p><h1>{ar?"الصحة في الحياة":"Health that fits"}<br/><em>{ar?"الحقيقية.":"real life."}</em></h1><span>{ar?"ميزانية، وقت، شغل، دراسة، سفر، رمضان — السياق جزء من الخطة.":"Budget, time, work, study, travel and Ramadan — context belongs in the plan."}</span></div><figure><img src="https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=1600" alt=""/></figure></section>
 <section className={styles.modes}><header><small>01 · LIFE MODE</small><h2>{ar?"إيه شكل يومك النهارده؟":"What kind of day is this?"}</h2><p>{ar?"اختيار السياق لا يحكم عليك؛ هو فقط يجعل يومياتك أذكى.":"Context is not a score. It simply makes your journal more useful."}</p></header><div>{modes.map(([en,arx])=><button className={mode===en?styles.on:""} onClick={()=>setMode(en)} key={en}>{ar?arx:en}</button>)}</div><button className={styles.save} onClick={()=>save("Life mode",mode)}>{saved==="Life mode"?(ar?"✓ اتحفظ":"✓ Saved"):(ar?"احفظ سياق اليوم":"Save today's context")}</button></section>
 <section className={styles.budget}><div className={styles.budgetCopy}><small>02 · BUDGET MEAL LAB</small><h2>{ar?"ابدأ بما عندك،":"Start with what you have,"}<br/><em>{ar?"مش بما ينقصك.":"not what you're missing."}</em></h2><p>{band}</p><label>{ar?"ميزانية تقريبية للفرد (جنيه)":"Approx. budget per person (EGP)"}<input inputMode="numeric" value={budget} onChange={e=>setBudget(e.target.value.replace(/[^0-9]/g,"").slice(0,4))}/></label></div><div className={styles.builder}><Picker n="PROTEIN" items={proteins} value={protein} set={setProtein} ar={ar}/><Picker n="STAPLE" items={bases} value={base} set={setBase} ar={ar}/><Picker n="VEGETABLE" items={veg} value={vegetable} set={setVegetable} ar={ar}/><aside><small>{ar?"وجبتك":"YOUR MEAL"}</small><strong>{meal}</strong><p>{ar?"اقتراح للتفكير والتنويع، وليس تسعيرًا لحظيًا أو وصفة علاجية.":"A practical composition prompt, not live pricing or a treatment plan."}</p><button onClick={()=>save("Meal",meal)}>{saved==="Meal"?(ar?"✓ في اليوميات":"✓ In journal"):(ar?"احفظ الوجبة":"Remember meal")}</button></aside></div></section>
 <section className={styles.teens}><div><small>03 · TEENS</small><h2>{ar?"مش دايت.":"Not a diet."}<br/><em>{ar?"مش محاضرة.":"Not a lecture."}</em></h2></div><div className={styles.teenGrid}><article><b>{ar?"طاقة اليوم":"ENERGY"}</b><p>{ar?"اربط الأكل والنوم والحركة بما تحس به، من غير درجات مثالية.":"Connect food, sleep and movement to how the day actually feels — no perfect scores."}</p></article><article><b>{ar?"أكل المدرسة والخروج":"REAL-WORLD FOOD"}</b><p>{ar?"اختيارات من الكانتين، الدروس، الخروج والأكل مع الأصحاب بدل قوائم ممنوعات.":"Think canteen, lessons, outings and eating with friends instead of forbidden-food lists."}</p></article><article><b>{ar?"تجربة صغيرة":"TINY EXPERIMENT"}</b><p>{ar?"غيّر حاجة واحدة لأيام قليلة وسجل ملاحظتك بدل ما تقلب حياتك كلها مرة واحدة.":"Change one thing for a few days and notice what happens instead of overhauling everything."}</p></article></div></section></div>
}
function Picker({n,items,value,set,ar}:{n:string;items:string[][];value:number;set:(n:number)=>void;ar:boolean}){return <div className={styles.picker}><small>{n}</small>{items.map((x,i)=><button className={value===i?styles.selected:""} onClick={()=>set(i)} key={x[0]}>{ar?x[1]:x[0]}</button>)}</div>}
