"use client";
import {useEffect,useMemo,useState} from "react";
type Food={id:string;name:string;category:string;portion:string;carbohydrate:string};
export default function FoodAtlasLive({add,go,ar}:{add:(t:string,v:string)=>void;go:(v:any)=>void;ar:boolean}){
 const [foods,setFoods]=useState<Food[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("All"),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/foods").then(r=>r.ok?r.json():null).then(data=>setFoods(Array.isArray(data?.foods)?data.foods:[])).catch(()=>setFoods([])).finally(()=>setLoading(false))},[]);
 const categories=useMemo(()=>["All",...Array.from(new Set(foods.map(f=>f.category)))],[foods]);
 const shown=foods.filter(f=>(category==="All"||f.category===category)&&`${f.name} ${f.category}`.toLowerCase().includes(q.toLowerCase()));
 return <section className="page atlasPage"><div className="pageHero compactHero"><small>{ar?"دليل الأكل المصري":"EGYPTIAN FOOD ATLAS"}</small><h1>{ar?<>أكل مألوف.<br/><em>وسياق مفيد.</em></>:<>Familiar food.<br/><em>Useful context.</em></>}</h1><p>{ar?"بيانات الدليل محملة من قاعدة NutClue العامة. التقديرات تعليمية وقد تختلف حسب الوصفة والكمية.":"Food references loaded from the public NutClue food database. Estimates are educational and vary by recipe and portion."}</p><div className="topicSearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} aria-label={ar?"ابحث في الأكل المصري":"Search Egyptian foods"} placeholder={ar?"ابحث: كشري، عيش، فول...":"Search koshari, bread, ful..."}/>{q&&<button onClick={()=>setQ("")} aria-label={ar?"امسح البحث":"Clear search"}>×</button>}</div></div><div className="atlasCats">{categories.map(x=><button key={x} className={category===x?"on":""} onClick={()=>setCategory(x)}>{x}</button>)}</div>{loading?<div className="emptyState"><b>{ar?"بنحمّل الدليل…":"Loading the atlas…"}</b></div>:<div className="atlasGrid">{shown.map(f=><article key={f.id}><div className="foodEmoji">🍽️</div><small>{f.category}</small><h2>{f.name}</h2><div className="foodNumbers"><span><b>{f.portion}</b>{ar?"الكمية":"portion"}</span><span><b>{f.carbohydrate}</b>{ar?"كربوهيدرات":"carbohydrate"}</span></div><div className="foodActions"><button onClick={()=>add("Food",`${f.name} · ${f.portion} · ${f.carbohydrate} carbohydrate reference`)}>{ar?"افتكر":"Remember"}</button></div></article>)}</div>}{!loading&&!shown.length&&<div className="emptyState"><b>{ar?"مفيش أكل مطابق.":"No food found."}</b><p>{ar?"جرّب اسم تاني.":"Try another search."}</p></div>}<div className="atlasBridge"><div><small>{ar?"معاك البطاقة؟":"HAVE THE PACK?"}</small><h2>{ar?"استخدم بطاقة المنتج الفعلية لما تقدر.":"Use the actual label when you can."}</h2></div><button onClick={()=>go("lens")}>{ar?"افتح العدسة ←":"Open Lens →"}</button></div></section>
}

