"use client";
import {useEffect,useMemo,useState} from "react";
type Food={id:string;name:string;name_en?:string;category:string;portion:string;portion_ar?:string;carbohydrate:string;source?:string;confidence?:string;reviewed_at?:string};
const categoryLabels:{[key:string]:string}={All:"الكل","Bread & grains":"خبز وحبوب",Legumes:"بقوليات","Mixed dishes":"أطباق مختلطة",Starches:"نشويات",Pastries:"مخبوزات",Sweets:"حلويات",Dairy:"ألبان",Fruit:"فاكهة",Vegetables:"خضار",Drinks:"مشروبات"};
const englishNames:{[key:string]:string}={"عيش بلدي":"Baladi bread","عيش شامي":"Shami bread","فول مدمس":"Ful medames","طعمية":"Taameya","أرز مطبوخ":"Cooked rice","رز بالشعرية":"Rice with vermicelli","مكرونة مطبوخة":"Cooked pasta","فريك":"Freekeh","برغل":"Bulgur","كشري":"Koshari","محشي":"Mahshi","محشي ورق عنب":"Stuffed vine leaves","محشي كرنب":"Stuffed cabbage","محشي كوسة":"Stuffed zucchini","حواوشي":"Hawawshi","فتة":"Fattah","ملوخية":"Molokhia","بطاطس مسلوقة":"Boiled potato","بطاطا":"Sweet potato","ذرة":"Corn","بسلة":"Peas","عدس":"Lentils","شوربة عدس":"Lentil soup","فاصوليا بيضا":"White beans","حمص":"Chickpeas","فطير مشلتت":"Feteer meshaltet","بسبوسة":"Basbousa","قطايف":"Qatayef","كنافة":"Konafa","أم علي":"Om Ali","أرز باللبن":"Rice pudding","كحك":"Kahk","زبادي سادة":"Plain yogurt","لبن":"Milk","تفاح":"Apple","موز":"Banana","برتقال":"Orange","مانجو":"Mango","عنب":"Grapes","بطيخ":"Watermelon","بلح / تمر":"Dates"};
const foodEmoji:{[key:string]:string}={"baladi-bread":"🥖","shami-bread":"🫓",ful:"🫘",taameya:"🧆",rice:"🍚","rice-vermicelli":"🍚",pasta:"🍝",freekeh:"🌾",bulgur:"🌾",koshari:"🍲",mahshi:"🍃","mahshi-grape":"🍃","mahshi-cabbage":"🥬","mahshi-zucchini":"🥒",hawawshi:"🥙",fattah:"🍲",molokhia:"🥬",potato:"🥔","sweet-potato":"🍠",corn:"🌽",peas:"🫛",lentils:"🫘","lentil-soup":"🥣","white-beans":"🫘",chickpeas:"🫘",feteer:"🫓",basbousa:"🍰",qatayef:"🥞",konafa:"🍰","om-ali":"🥣","rice-pudding":"🥣",kahk:"🍪",yogurt:"🥛",milk:"🥛",apple:"🍎",banana:"🍌",orange:"🍊",mango:"🥭",grapes:"🍇",watermelon:"🍉",dates:"🌴"};
const arabicPortions:{[key:string]:string}={"1 medium piece":"قطعة متوسطة","½ cup":"نصف كوب","3 pieces":"٣ قطع","⅓ cup":"ثلث كوب","1 plate":"طبق واحد","6 small pieces":"٦ قطع صغيرة","1 small":"واحدة صغيرة","½ cup cooked":"نصف كوب مطبوخ","1 small piece":"قطعة صغيرة","1 small cup":"كوب صغير"};
const arabicSources:{[key:string]:string}={estimated:"تقدير تعليمي",variable:"يختلف حسب الوصفة",label:"راجع البطاقة"};
export default function FoodAtlasLive({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:any)=>void;ar:boolean}){
 const [foods,setFoods]=useState<Food[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("All"),[loading,setLoading]=useState(true),[error,setError]=useState(false),[savedId,setSavedId]=useState<string|null>(null);
 useEffect(()=>{let active=true;fetch("/api/foods").then(r=>r.ok?r.json():null).then(data=>{if(!active)return;if(Array.isArray(data?.foods))setFoods(data.foods);else setError(true)}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const categories=useMemo(()=>["All",...Array.from(new Set(foods.map(f=>f.category)))],[foods]);
 const shown=foods.filter(f=>(category==="All"||f.category===category)&&`${f.name} ${englishNames[f.name]||""} ${f.category}`.toLowerCase().includes(q.toLowerCase()));
 const label=(f:Food)=>ar?f.name:(f.name_en||englishNames[f.name]||f.name),portion=(f:Food)=>ar?(f.portion_ar||arabicPortions[f.portion]||f.portion):f.portion;
 return <section className="page atlasPage"><div className="pageHero compactHero"><small>{ar?"دليل الأكل المصري":"EGYPTIAN FOOD ATLAS"}</small><h1>{ar?<>أكل مألوف.<br/><em>وسياق مفيد.</em></>:<>Familiar food.<br/><em>Useful context.</em></>}</h1><p>{ar?"مراجع تعليمية من دليل Ilama Bloom. التقديرات قد تختلف حسب الوصفة والمنتج والكمية.":"Food references from the Ilama Bloom educational atlas. Estimates vary by recipe, product and portion."}</p><div className="topicSearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} aria-label={ar?"ابحث في الأكل المصري":"Search Egyptian foods"} placeholder={ar?"ابحث: كشري، عيش، فول...":"Search koshari, bread, ful..."}/>{q&&<button type="button" onClick={()=>setQ("")} aria-label={ar?"امسح البحث":"Clear search"}>×</button>}</div></div><div className="atlasCats" aria-label={ar?"فئات دليل الأكل":"Food categories"}>{categories.map(x=><button type="button" key={x} className={category===x?"on":""} aria-pressed={category===x} onClick={()=>setCategory(x)}>{ar?(categoryLabels[x]||x):x}</button>)}</div>{loading?<div className="emptyState" role="status"><b>{ar?"بنحمّل الدليل…":"Loading the atlas…"}</b></div>:error?<div className="emptyState" role="alert"><b>{ar?"الدليل غير متاح مؤقتًا.":"The atlas is temporarily unavailable."}</b><p>{ar?"جرّب تحديث الصفحة بعد لحظات.":"Refresh the page in a moment."}</p></div>:<div className="atlasGrid">{shown.map(f=><article key={f.id}><div className="foodEmoji">{foodEmoji[f.id]||"🍽️"}</div><small>{ar?(categoryLabels[f.category]||f.category):f.category}</small><h2>{label(f)}</h2><div className="foodNumbers"><span><b>{portion(f)}</b>{ar?"الكمية":"portion"}</span><span><b>{f.carbohydrate}</b>{ar?"كربوهيدرات":"carbohydrate"}</span></div><p className="foodMeta">{ar?`المصدر: ${f.source||"مرجع Ilama Bloom تعليمي"} · ${f.confidence==="label"?"راجع البطاقة":"تقدير تعليمي"}`:`Source: ${f.source||"Ilama Bloom reference"} · ${f.confidence||"estimated"}`}</p><div className="foodActions"><button type="button" aria-live="polite" onClick={async()=>{const ok=await add("Food",`${label(f)} · ${portion(f)} · ${f.carbohydrate} carbohydrate reference`);if(ok){setSavedId(f.id);setTimeout(()=>setSavedId(x=>x===f.id?null:x),1800)}}}>{savedId===f.id?(ar?"تم الحفظ ✓":"Saved ✓"):(ar?"افتكر":"Remember")}</button></div></article>)}</div>}{!loading&&!error&&!shown.length&&<div className="emptyState" role="status"><b>{ar?"مفيش أكل مطابق.":"No food found."}</b><p>{ar?"جرّب اسم تاني.":"Try another search."}</p><button type="button" onClick={()=>{setQ("");setCategory("All")}}>{ar?"إعادة ضبط الدليل":"Reset atlas"}</button></div>}<div className="atlasBridge"><div><small>{ar?"معاك البطاقة؟":"HAVE THE PACK?"}</small><h2>{ar?"استخدم بطاقة المنتج الفعلية لما تقدر.":"Use the actual label when you can."}</h2></div><button type="button" onClick={()=>go("lens")}>{ar?"افتح العدسة ←":"Open Lens →"}</button></div></section>
}

