"use client";
import {useEffect,useState} from "react";
import styles from "./KidsEditorial.module.css";
type Mission={id:string;title_en:string;title_ar:string;prompt_en:string;prompt_ar:string;options_en:string[];options_ar:string[];answer:number;explanation_en:string;explanation_ar:string};
export default function KidsEditorial({ar,saveProgress}:{ar:boolean;saveProgress:(key:string,score:number)=>Promise<boolean>}){
 const [missions,setMissions]=useState<Mission[]>([]),[mission,setMission]=useState(0),[answer,setAnswer]=useState<number|null>(null),[plate,setPlate]=useState<string[]>([]);
 useEffect(()=>{fetch("/api/learning-missions").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.missions)&&setMissions(d.missions)).catch(()=>{})},[]);
 const local:Mission={id:"local-carb",title_en:"Carb clue",title_ar:"دليل الكربوهيدرات",prompt_en:"Which one contains carbohydrate?",prompt_ar:"أنهي واحد فيهم فيه كربوهيدرات؟",options_en:["Chicken","Baladi bread","Egg"],options_ar:["فراخ","عيش بلدي","بيضة"],answer:1,explanation_en:"Bread is a grain food and contains carbohydrate.",explanation_ar:"العيش من الحبوب ويحتوي على كربوهيدرات."}; const list=missions.length?missions:[local],m=list[mission%list.length]; const opts=ar?m.options_ar:m.options_en;
 const foods=[["🥖","Baladi bread","عيش بلدي"],["🍚","Rice","أرز"],["🍗","Chicken","فراخ"],["🥒","Cucumber","خيار"],["🍊","Orange","برتقال"],["🥛","Milk","لبن"]];
 return <div className={styles.page}><section className={styles.hero}><div><p className={styles.kicker}>{ar?"الأطفال · العائلة":"KIDS · FAMILY"}</p><h1>{ar?<>لعقول وأجسام<br/><em>تنمو.</em></>:<>For growing<br/><em>minds & bodies.</em></>}</h1><p>{ar?"تعلم مرح ومناسب للعمر يساعد الأطفال على فهم الطعام بدون خوف أو أحكام.":"Playful, age-appropriate learning that helps kids understand food without fear or judgement."}</p></div><figure><img src="https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=1800" alt=""/></figure></section>
 <section className={styles.learn}><div className={styles.intro}><p className={styles.kicker}>01 · {ar?"اعرف الطعام":"KNOW YOUR FOOD"}</p><h2>{ar?"الكربوهيدرات موجودة في أماكن كثيرة.":"Carbohydrates live in lots of familiar foods."}</h2></div><div className={styles.groups}>{[[ar?"الحبوب والنشويات":"Grains & starches","🍞",ar?"عيش، أرز، مكرونة، بطاطس":"Bread, rice, pasta, potatoes"],[ar?"الفاكهة":"Fruit","🍊",ar?"الفاكهة الكاملة جزء من الصورة":"Whole fruit is part of the picture"],[ar?"اللبن والزبادي":"Milk & yogurt","🥛",ar?"قد يساهمان بالكربوهيدرات":"They can contribute carbohydrate"],[ar?"البقوليات":"Legumes","🫘",ar?"عدس، فول، حمص":"Lentils, ful, chickpeas"]].map(([t,e,c])=><article key={t}><b>{e}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className={styles.game}><div className={styles.gameCopy}><p className={styles.kicker}>02 · {ar?"اصنع وجبتك":"BUILD YOUR PLATE"}</p><h2>{ar?"اختار ما تحب أن تضعه على الطبق.":"Choose what belongs on your plate."}</h2><p>{ar?"لا توجد وجبة مثالية هنا — الهدف أن نتعرف على الطعام ونتكلم عنه.":"There is no perfect plate here — the goal is to notice food and talk about it."}</p></div><div className={styles.builder}><div className={styles.foods}>{foods.map(([e,enName,arName])=><button key={enName} onClick={()=>setPlate(p=>p.includes(enName)?p:p.length<6?[...p,enName]:p)}><b>{e}</b><span>{ar?arName:enName}</span></button>)}</div><div className={styles.plate}>{plate.length?plate.map(x=>{const f=foods.find(y=>y[1]===x);return <span key={x}>{f?.[0]}</span>}):<small>{ar?"ابدأ بإضافة طعام":"Add something to begin"}</small>}</div><button className={styles.reset} onClick={()=>setPlate([])}>{ar?"ابدأ من جديد":"Start again"}</button></div></section>
 <section className={styles.mission}><figure><img src="https://images.pexels.com/photos/3661350/pexels-photo-3661350.jpeg?auto=compress&cs=tinysrgb&w=1400" alt=""/></figure><div><p className={styles.kicker}>03 · {ar?"تحدي سريع":"QUICK MISSION"}</p><h2>{ar?m.prompt_ar:m.prompt_en}</h2><div className={styles.options}>{opts.map((o,i)=><button className={answer===i?(i===m.answer?styles.correct:styles.wrong):""} key={o} onClick={async()=>{setAnswer(i);if(i===m.answer)await saveProgress(m.id,1)}}>{o}</button>)}</div>{answer!==null&&<p className={styles.explain}>{ar?m.explanation_ar:m.explanation_en}</p>}<button className={styles.next} onClick={()=>{setAnswer(null);setMission(x=>(x+1)%list.length)}}>{ar?"التحدي التالي":"Next mission"} <span>→</span></button></div></section></div>
}