"use client";
import {useMemo,useState} from "react";
import styles from "./WeeklyBloom.module.css";
type Entry={id?:string;type:string;value:string;at:string};
export default function WeeklyBloom({entries,go,add,ar}:{entries:Entry[];go:(v:"journal")=>void;add:(t:string,v:string)=>Promise<boolean>|boolean;ar:boolean}){
 const [reflection,setReflection]=useState(""); const week=useMemo(()=>entries.filter(e=>Date.now()-new Date(e.at).getTime()<7*86400000),[entries]);
 const count=(types:string[])=>week.filter(e=>types.includes(e.type)).length; const days=new Set(week.map(e=>new Date(e.at).toISOString().slice(0,10))).size;
 const cards=[[ar?"التغذية والمياه":"Nourish",count(["Meal","Food","Food label","Water"])],[ar?"الحركة":"Move",count(["Steps","Move","Work / activity"])],[ar?"الراحة والطاقة":"Rest",count(["Sleep","Energy"])],[ar?"الإحساس والجسد":"Feel",count(["Feeling","Symptom","Symptom severity"])]];
 const mode=week.find(e=>e.type==="Life mode")?.value;
 return <section className={styles.page}><header><p>{ar?"إزهار الأسبوع · آخر 7 أيام":"WEEKLY BLOOM · LAST 7 DAYS"}</p><h1>{ar?"شوف أسبوعك، من غير درجات.":"See your week, without a score."}</h1><span>{ar?"ملخص هادئ مبني فقط على ما اخترت تسجيله. لا توجد أيام فاشلة ولا أهداف إجبارية.":"A calm reflection built only from what you chose to record. No failed days and no compulsory targets."}</span></header><div className={styles.totals}><article><b>{week.length}</b><span>{ar?"لحظة محفوظة":"moments remembered"}</span></article><article><b>{days}</b><span>{ar?"أيام فيها سياق — ليس هدفًا":"days with context — not a target"}</span></article></div><div className={styles.grid}>{cards.map(([title,value],i)=><article key={String(title)}><small>0{i+1}</small><h2>{title}</h2><b>{value}</b></article>)}</div><aside><p>{ar?"السياق الذي ظهر":"CONTEXT THAT SHOWED UP"}</p><h2>{mode||(ar?"لم تسجل سياقًا محددًا — وهذا طبيعي.":"No specific life mode recorded — and that is fine.")}</h2><button onClick={()=>go("journal")}>{ar?"راجع الخط الزمني":"Review timeline"} →</button></aside><div className={styles.reflect}><p>{ar?"انعكاس صغير":"A SMALL REFLECTION"}</p><h2>{ar?"ما الشيء الذي تريد أن تتذكره من هذا الأسبوع؟":"What feels worth remembering from this week?"}</h2><textarea maxLength={180} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder={ar?"ملاحظة قصيرة تكفي...":"A short note is enough..."}/><button disabled={!reflection.trim()} onClick={async()=>{if(await add("Weekly reflection",reflection.trim()))setReflection("")}}>{ar?"احفظ في اليوميات":"Save reflection"} →</button></div></section>
}