import {neon} from "@neondatabase/serverless";
import {currentUser} from "../../../lib/auth/server";
function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.ILAMA_BLOOM_DATABASE_URL||process.env.ILAMA_BLOOM_POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}
async function ensure(sql:ReturnType<typeof neon>){await sql`CREATE TABLE IF NOT EXISTS public.user_profiles (user_id text PRIMARY KEY, full_name text NOT NULL DEFAULT '', phone text NOT NULL DEFAULT '', birth_date date, country text NOT NULL DEFAULT '', language text NOT NULL DEFAULT 'en', conditions text NOT NULL DEFAULT '', medications text NOT NULL DEFAULT '', allergies text NOT NULL DEFAULT '', goals text NOT NULL DEFAULT '', onboarding_complete boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store"}});
const clean=(value:unknown,max:number)=>String(value||"").trim().slice(0,max);
export async function GET(){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);const rows=await sql`SELECT full_name,phone,birth_date,country,language,conditions,medications,allergies,goals,onboarding_complete,updated_at FROM public.user_profiles WHERE user_id=${u.id} LIMIT 1`;return json({profile:rows[0]||null,user:{name:u.name||"",email:u.email}})}catch(error){console.error("profile GET failed",error);return json({error:"Unable to load profile"},500)}}
export async function POST(request:Request){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const body=await request.json().catch(()=>null);if(!body)return json({error:"Invalid JSON"},400);const fullName=clean(body.fullName,100),phone=clean(body.phone,40),country=clean(body.country,80),language=body.language==="ar"?"ar":"en",conditions=clean(body.conditions,800),medications=clean(body.medications,800),allergies=clean(body.allergies,800),goals=clean(body.goals,800);const rawBirth=clean(body.birthDate,10);const birthDate=/^\d{4}-\d{2}-\d{2}$/.test(rawBirth)?rawBirth:null;if(!fullName)return json({error:"Full name is required"},400);const sql=db();await ensure(sql);const rows=await sql`INSERT INTO public.user_profiles (user_id,full_name,phone,birth_date,country,language,conditions,medications,allergies,goals,onboarding_complete) VALUES (${u.id},${fullName},${phone},${birthDate},${country},${language},${conditions},${medications},${allergies},${goals},true) ON CONFLICT (user_id) DO UPDATE SET full_name=${fullName},phone=${phone},birth_date=${birthDate},country=${country},language=${language},conditions=${conditions},medications=${medications},allergies=${allergies},goals=${goals},onboarding_complete=true,updated_at=now() RETURNING full_name,phone,birth_date,country,language,conditions,medications,allergies,goals,onboarding_complete,updated_at`;return json({profile:rows[0]},201)}catch(error){console.error("profile POST failed",error);return json({error:"Unable to save profile"},500)}}
export async function DELETE(){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);await sql`DELETE FROM public.user_profiles WHERE user_id=${u.id}`;return json({ok:true})}catch(error){console.error("profile DELETE failed",error);return json({error:"Unable to delete profile"},500)}}
